### ISSUE TITLE
Open new tab when clicking on page in nav

### ISSUE THREAD

**Issue by devonzuegel** [pengx17/logseq-plugin-tabs#12]
The behavior of links in the sidebar (e.g. Favorites, Recent) doesn't match the behavior of links in the page.

When I click links in the page while clicking `Cmd` on the Mac, it creates a new tab as I expect. But when I do the same for links in the sidebar, it replaces the current tab. I'd expect the behavior in the nav to match the behavior in pages.

---

P.S. this is an awesome plugin! Thanks for writing it.

**Comment by pengx17** [comment]
Thanks @devonzuegel, I will implement this in the next week :)

**Comment by pengx17** [comment]
Fixed in https://github.com/pengx17/logseq-plugin-tabs/releases/tag/v1.8.5

**Comment by devonzuegel** [comment]
So fast, wow!
