### ISSUE TITLE
Styling tabs?

### ISSUE THREAD

**Issue by prurph** [pengx17/logseq-plugin-tabs#13]
Is it possible to style the tabs? I tried overriding styles in my custom.css but the rules did not seem to be respected.

**Comment by pengx17** [comment]
No, tabs plugin renders tabs in iframe, which is no affected by custom.css. I think I can add an option to pass styles into tabs plugins, if you think the requirement is very strong

**Comment by prurph** [comment]
Thanks for responding. I could try adding it. What do you think is the best way to pass in styles? Perhaps use the logseq API to read the custom.css note if it exists and load from there?

**Comment by pengx17** [comment]
I am thinking about allowing the user to put CSS string into the plugin settings as an advanced config, which will take effect in the iframe context. What do you think?

**Comment by prurph** [comment]
That sounds like a good approach. I didn't realize plugins could have settings yet as per [this thread](https://discuss.logseq.com/t/plugin-settings/3138).

**Comment by mkosma** [comment]
@pengx17 any update on this? unfortunately tabs aren't looking too visible with my logseq dark-themed css

**Comment by pengx17** [comment]
@mkosma now the user can enable customizing the tabs styles through custom.css

<img width="941" alt="image" src="https://user-images.githubusercontent.com/584378/174218374-f29bf25e-f829-4bc4-b6a8-1f3ef7c7c180.png">

**Comment by mkosma** [comment]
Fantastic! Thank you very much.

**Comment by mkosma** [comment]
@pengx17 FYI I'm using this with your [logseq-dev-theme](https://github.com/pengx17/logseq-dev-theme/) -- in case anyone else is puzzled on how to do it, here's what I inserted into my custom.css file. 

I still love the magic of how Logseq shows changes live when you update the custom.css file.

```
/* tabs plugin custom css */

.dark .logseq-tab[data-active=true] {
  background-color: #999999;
}

.dark .logseq-tab[data-active=false] {
  background-color: #444444;
}
```
