### ISSUE TITLE
Shortcut conflicts

### ISSUE THREAD

**Issue by trickard1000** [pengx17/logseq-plugin-tabs#14]
Hi.

When tabs is not running in Logseq Desktop 0.5.4 on Windows 10 my shortcut for a question mark (?) - ctrl+alt+w - functions while my keyboard is set to Portuguese.
When tabs is running, the same shortcut closes the tab I am in then takes me to todays journal page. 
It seems the programmed shortcut for closing the current tab unfortunately conflicts with my ? shortcut.
Maybe not worth a fix for you, but options to choose shortcuts would be lovely.

Thanks, Thomas.

**Comment by pengx17** [comment]
The current implementation of closing tabs is going to be refactored later. For your convenience, I will remove the shortcuts for now. :)

**Comment by pengx17** [comment]
Please see this. Closing tabs have been changed to "CTRL+SHIFT+W"
![image](https://user-images.githubusercontent.com/584378/161884743-ddca02f0-b5e0-46ce-a2d8-e11d818608b1.png)
