### ISSUE TITLE
keyboard shortcut overrides application defaults

### ISSUE THREAD

**Issue by feigaoxyz** [pengx17/logseq-plugin-tabs#15]
I'm on Mac and `Cmd+w` should close the LogSeq window.
However, after using the plugin, `cmd+w` no longer close the logseq window, (if there is no *tabs*, i.e., only the default view).

**Comment by pengx17** [comment]
I think I have removed the shortcut in the latest version. Let me take alook

**Comment by Alejandro-Stolz** [comment]
Is there any way the shortcuts could be customized, I would find them useful. Thanks for this amazing plugin!

**Comment by bambirombi** [comment]
what is now the shortcut to close tab? Always closes logseq with that shortcut, not tabs. Thanks.

**Comment by pengx17** [comment]
Hi @bambirombi , due to the limitation to Logseq's plugin API, there is no way to bind "CTRL+W" to override the default app closing behavior.
BTW I have updated this section:
![image](https://user-images.githubusercontent.com/584378/161884469-486d8da2-71da-43f0-9f82-cfd9e64e2c25.png)
