### ISSUE TITLE
Feature request: Show block content as title of tab when **zoom in**.

### ISSUE THREAD

**Issue by mzwlevi** [pengx17/logseq-plugin-tabs#16]
When **zoom in** node, the title of tab is **page name/id**.
Could you use the block content to replace the id?
Because when use the id, we do not know what's the content of tab.

For example:
After **zoom in** the node which content is **#annotaion**, but the tab show its id. When I switch to another tab, I don't know what this tab is.
<img width="888" alt="Screen Shot 2022-01-28 at 10 15 28" src="https://user-images.githubusercontent.com/78029539/151475905-4c82e44e-1d38-4db3-817d-8ea58b18bd8f.png">

**Comment by pengx17** [comment]
This is a good idea. I will think about it.

**Comment by brandon-toner** [comment]
Another option on this could be the ability to manually rename a tab. That would work for me.
