### ISSUE TITLE
Close the tab by  clicking the middle-button of mouse  on it

### ISSUE THREAD

**Issue by cloudrflight** [pengx17/logseq-plugin-tabs#17]
[microsoft windows] I often use the middle-button of mouse to close the tabs in chrome browser，I don't know if any other has the same habbit,. 
I   request a feature  that close the tab by  clicking the middle-button of mouse  on it.

**Comment by KoStard** [comment]
I agree, without this, it's quite hard to close multiple tabs quickly. The size of the tab label is different and hence the X is located in different places.

I would also be interested to contribute to this project and add the feature. Will check the guidelines, but if you have any tips, would appreciate them :)
