### ISSUE TITLE
Glitch on UI

### ISSUE THREAD

**Issue by Explorare** [pengx17/logseq-plugin-tabs#19]
![image](https://user-images.githubusercontent.com/5090766/161458108-1a1904dc-3c2e-4ff3-8b6e-769e4ffadec9.png)

The tabs UI blocks part of title area. Is this a intended behavior or not?

Logseq v0.6.5
Tabs v1.9.0

**Comment by pengx17** [comment]
Please try the latest version. I have added padding to the main area to avoid the collision issue.

**Comment by Explorare** [comment]
Thanks for the fix. And I forgot to note that the theme I'm having issue with is Bonofix. The default theme don't have this issue with the tabs v1.9.2 .
