### ISSUE TITLE
Ctrl+click not work

### ISSUE THREAD

**Issue by red-co** [pengx17/logseq-plugin-tabs#20]
in logseq 0.64, it not work when ctrl+click to link ,only work with block，
#bug

**Comment by red-co** [comment]
The failure occurred, but I restarted the program and it worked fine, I'm sorry

**Comment by pengx17** [comment]
> The failure occurred, but I restarted the program and it worked fine, I'm sorry

No need to feel sorry! I think there are some cases that ctrl click does not work indeed.
