### ISSUE TITLE
Feature Request: Unpin/ Delete all Tabs 

### ISSUE THREAD

**Issue by s-kyy** [pengx17/logseq-plugin-tabs#21]
Hello, I'm running into a similar issue for the second situation in #8 . For example, if I try to pin a view of a zoomed in bullet it sometimes loses the page while it's pinned, so now I can't unpin it.  

I tried restarting logseq by opening and closing the software, and tried clicking on the tab and running the close tab command but no dice. 

When I try to click on the pane, it unfocuses from it and the title of the window would say "Page no longer exists!". I can still see the same bullet note on the original page it came from so it's quite odd. 

As a quick work around, is it possible to implement an "Unpin All Tabs" command just so I can delete the pages manually? Or a "Remove all tabs" to purge all the tabs? If anything I'll wait patiently for the mentioned bug to be fixed.

Edit: Another solution could be to also include the Tab Delete button to pinned tabs. I really only use the the pinning feature when I want to open links to a new tab, but I would like to delete it if I want to. 

Many thanks, I've been enjoying this plugin a lot. 

Logseq Version: 0.65 (Desktop)
Machine: Windows 10
Plugin version : 1.9.2

**Comment by s-kyy** [comment]
When I was reading over the README file again, I noticed that double-clicking can also unpin the tab as well (whoops!), so that solves the issue I was running into. Feel free to close this issue if the feature isn't something you want to work on.

**Comment by pengx17** [comment]
> When I try to click on the pane, it unfocuses from it and the title of the window would say "Page no longer exists!". I can still see the same bullet note on the original page it came from so it's quite odd.

I think this is something I can try to optimize. Thanks for bringing up this again! Closing this issue and favoring #8

**Comment by HlexNC** [comment]
It would be nice if one could just right click and press unpin 😆
