### ISSUE TITLE
Feature: Cycle Through Tabs with Ctrl+Tab and Ctrl+Shift+Tab 

### ISSUE THREAD

**Issue by s-kyy** [pengx17/logseq-plugin-tabs#22]
Hi I would also like to suggest a feature for those that like to navigate more by keyboard only. 

I'd like to propose being able to change tabs using keyboard shortcuts. The behaviour would preferably be toggable between two different behaviours:

Recency (Similar to FireFox browser)
- Ctrl+Tab: Shows next most recent tab (cycles to the least recent tab when there are no more recent ones)
- Ctrl+Shift+Tab: Shows previous most recent tab (cycles to the most recent tab when we reach the least recent tab)

Position in the list of tabs
- Ctrl+Tab: Navigate to the right tab
- Ctrl+Shift+Tab: Navigate to the left tab

For the looping behaviour maybe that could be made optional too if that's feasible. 

Being able to customize the shortcuts would also be nice but not necessary :)

**edited for typos**

**Comment by pengx17** [comment]
This is a pretty valid suggestion! I will take some time to do it this week :)

**Comment by pengx17** [comment]
Done! Please check https://github.com/pengx17/logseq-plugin-tabs/releases/tag/v1.10.0
