### ISSUE TITLE
[feature] Allow user to customize the shortcuts

### ISSUE THREAD

**Issue by kaushalmodi** [pengx17/logseq-plugin-tabs#24]
Hello,

I have a custom binding to Ctrl+W in my Logseq config.edn. So when I install this plugin, I get a warning popup saying that there's a clash for the Ctrl+W binding. 

But I cannot customize that binding for this plugin.

Can you please allow a way for the users to set their own bindings? Maybe using a settings.json file, or a new section that we can put in the logset config.edn? Or something else?

Thanks!

**Comment by pengx17** [comment]
Fixed in https://github.com/pengx17/logseq-plugin-tabs/releases/tag/v1.11.0
