### ISSUE TITLE
my plugin is not working!!

### ISSUE THREAD

**Issue by wenjing100** [pengx17/logseq-plugin-tabs#25]
I've downloaded the plugin as follows:
![image](https://user-images.githubusercontent.com/55542032/164677802-b85e77e9-0c19-4d3c-9442-c44fbbd0296b.png)
**while I ctrl + click a refblock-------nothing happened???? like this** 
![image](https://user-images.githubusercontent.com/55542032/164678119-a84aa404-6ce0-4967-8335-85e37d586392.png)

**just nothing!**

what did I miss??

**Comment by pengx17** [comment]
How did you download this plugin? Via the marketplace or download the source code directly?

**Comment by wenjing100** [comment]
downloaded it from github release zip
![image](https://user-images.githubusercontent.com/55542032/164688334-13cc82de-9b69-4d9b-96c3-a72fdc79c9a9.png)
and unfolded in .logseq/plugin/logseq-tabs

and add the plugin manually

**Comment by wenjing100** [comment]
my logseq version is 0.6.6 by the way

**Comment by wenjing100** [comment]
would it possible that the plugin will conflit with any other plugins? my active plugins as follows:
![image](https://user-images.githubusercontent.com/55542032/164692183-a87ca491-3329-4224-9c02-929484fde527.png)

emmm.........

**Comment by pengx17** [comment]
I doubt it would collide with other plugins. So all other plugins could work except for the tabs plugin?
Do you have any errors in the dev tools console btw?

**Comment by wenjing100** [comment]
yes , neither does logseq-plugin-togen
![image](https://user-images.githubusercontent.com/55542032/164872968-19cc98d6-fc80-4eff-8a3a-e1d973500f76.png)

**Comment by wenjing100** [comment]
do yo have any clue?

**Comment by pengx17** [comment]
> do yo have any clue?

What if you disable all others except tabs plugin?

**Comment by wenjing100** [comment]
> > do yo have any clue?
> 
> What if you disable all others except tabs plugin?

of no use, even if restarted logseq. 
![image](https://user-images.githubusercontent.com/55542032/164971800-33002bed-25fc-43e8-addf-9581e410ad80.png)
![image](https://user-images.githubusercontent.com/55542032/164971811-dbf8eaa7-e923-41b2-9c96-bb196729c345.png)

**Comment by pengx17** [comment]
I am sorry, I could not infer what is the issue on your side :(

**Comment by wenjing100** [comment]
thank you all the way ! ~~ cry me a river, how i wish this pugin could work

**Comment by pengx17** [comment]
Could you please reload the app and check this log in the dev tools?

<img width="1206" alt="image" src="https://user-images.githubusercontent.com/584378/165226100-5556a582-7507-4197-83a0-0046b48611c2.png">

**Comment by wenjing100** [comment]
> Could you please reload the app and check this log in the dev tools?
> 
> <img alt="image" width="1206" src="https://user-images.githubusercontent.com/584378/165226100-5556a582-7507-4197-83a0-0046b48611c2.png">

![image](https://user-images.githubusercontent.com/55542032/165263904-6306d12c-513d-4158-82e7-3f8c2ebec38d.png)

**Comment by pengx17** [comment]
The entry field looks suspicious to me. The tabs plugin should NEVER had such entry that starts with `lsp://`.
Can you please:
1. run `localStorage.set("debug", "LSPlugin:core")` in dev console
2. reload the app
3. copy & paste the messages start starts with `LSPlugin:core`. 

e.g., this is mine:
<img width="782" alt="image" src="https://user-images.githubusercontent.com/584378/165327420-0b4b9e19-9b35-4c74-a2c7-c179f47c7263.png">

**Comment by wenjing100** [comment]
> 
run the code `localStorage.setItem("debug", "LSPlugin:core")` on console board and press `enter` to run it . then press 'x' to close the app.
open my app again, ' ctrl + shift + i '  nothing changed. no "LSplugin:core" could be seen
is there any sepcific way to reload the app? or do I have to download some tools to support my devtool?

**Comment by pengx17** [comment]
Yes, you should be able to reload the app by CTRL+R.

**Comment by wenjing100** [comment]
except turn the object shows as a table, no "LSPlugin:core" consoled still
![image](https://user-images.githubusercontent.com/55542032/165495874-33bb607e-aa44-467e-8a1a-ac5744d33218.png)

**Comment by pengx17** [comment]
Have you tried to install via the Marketplace? And can you please give me the plugin directory path for tabs?

**Comment by wenjing100** [comment]
> Have you tried to install via the Marketplace? And can you please give me the plugin directory path for tabs?
> 
> I have went through how Logseq bootstrap plugins. I guess the root cause is that you put plugins in a folder inside of Logseq's root folder, and Logseq will think that it is a plugin installed in the Logseq plugin Marketplace panel (not downloaded directly in GitHub releases pages). There is a security restriction for plugins installed this way.
> 
> I think your problem will be gone if you either
> 
> * move the plugins folder to another place that is not a descendent of the Logseq folder
> * or, install Tabs plugin via the marketplace panel
> 
> A note for myself on bypassing the security checks
> 
> * if the plugin is not inside of the dot root of Logseq
> * AND the `effect` property in the plugin metadata is true
> 
> Adding @xyhp915 for awareness.

***
bravo~~ I changed the folder of the plugin and it finally worked ! Thank you very much !!

**Comment by pengx17** [comment]
Glad to hear that! Glad to see your problem is resolved :D
I am closing this issue.
