### ISSUE TITLE
[feature request] Support custom keyboard shortcut

### ISSUE THREAD

**Issue by mifas** [pengx17/logseq-plugin-tabs#26]
Please enable support to change the keyboard shortcut. For example, I'd prefer to use `CMD + P` for Search pages in logseq
Is there way to add customize the shortcuts?

**Comment by peizh** [comment]
`CMD + P` is the default search page shortcut on Mac. Everytime I search a page I end up pinned one page. No wonder after a whole day I have many pages pinned 😅

**Comment by pengx17** [comment]
Released in https://github.com/pengx17/logseq-plugin-tabs/releases/tag/v1.11.0
