### ISSUE TITLE
[bug] Unable to undefine a keyboard shortcut

### ISSUE THREAD

**Issue by kaushalmodi** [pengx17/logseq-plugin-tabs#28]
Hello,

Thank you for adding the customization options for the key bindings.

I would like to customize some key bindings to be "nothing". If I leave them blank, I see these errors

![image](https://user-images.githubusercontent.com/3578197/165344317-da20b8b8-5708-41bd-8ee1-06fdf0ea8dc6.png)

Is there a right way for unbinding the shortcuts?

**Comment by pengx17** [comment]
Sure, I will fix this soon. Thanks for your suggestion!
