### ISSUE TITLE
ctrl + click on an alias link doesn't open the "mother page"

### ISSUE THREAD

**Issue by PierreBouchet** [pengx17/logseq-plugin-tabs#29]
Hi
I think the title says it all.
My page name is : "main page". One of this page's aliases is "Main page variant"
If i click on link called [[main page variant]], it opens "main page". If i ctrl + click it opens "main page variant".
It should in both cases open "main page", shouldn't it ?

Thanks for your work.

**Comment by pengx17** [comment]
🤔 I thought this is an issue I have fixed a long time ago. Will take a look why it still exists.
