### ISSUE TITLE
Help with Installation

### ISSUE THREAD

**Issue by ConstantinosM** [pengx17/logseq-plugin-tabs#3]
I have cloned the repo and in dev mode in logseq I have loaded the plugin. However it doesn't work (CMD + click):

![image](https://user-images.githubusercontent.com/25111975/131763413-130c1f9b-b834-4464-9dd8-6f47f67b5026.png)

It is a very useful plugin so any help to make it work would be great!

**Comment by pengx17** [comment]
Please download the one in the [release page](https://github.com/pengx17/logseq-plugin-tabs/releases):
![Uploading image.png…]()
