### ISSUE TITLE
一键关闭所有 tabs

### ISSUE THREAD

**Issue by gsgqgyq** [pengx17/logseq-plugin-tabs#31]
rt，可以一键关闭非固定 tabs 吗？就像浏览器一样，关闭所有窗口。

使用时间长了窗口就变的特别多。

**Comment by pengx17** [comment]
增加了一个命令, "Close all tabs", 可以通过 CTRL(MOD)+SHIFT+P 调出：
<img width="894" alt="image" src="https://user-images.githubusercontent.com/584378/166871380-3475cff2-9bea-4dab-aa12-16f931731058.png">
