### ISSUE TITLE
[feature request] disabling shortcuts

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [pengx17/logseq-plugin-tabs#34]
Hi!

I don't use the "pin" feature and it's conflicting with the default of "automatic linker".

I think it would be good if entering "disabled" (or checking a "disabled" box or whatever) could disable a given shortcut.

Thanks!

**Comment by pengx17** [comment]
You can give an empty shortcut in the setting to disable the shortcut.
<img width="443" alt="image" src="https://user-images.githubusercontent.com/584378/168419260-cd131eb6-8c56-4237-b386-b8bea4287354.png">

**Comment by thiswillbeyourgithub** [comment]
Thanks ! I thought I tried it and it didn't work.
My apologies and have a nice day!
