### ISSUE TITLE
Tab UI position

### ISSUE THREAD

**Issue by usoonees** [pengx17/logseq-plugin-tabs#37]
Is it possible to put tab in header?  There are some space for it.

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/56818734/169016645-9133480c-7382-43a0-8f2c-36223c372d70.png">

![image](https://user-images.githubusercontent.com/56818734/169016526-20f07962-7a3c-422f-9967-2367ed04ab8a.png)

I try to change the top attribute of UI inline style, but I can't click tab after that operation.

**Comment by Gitbreast** [comment]
Curious about this. Did you make it work then close the issue?

**Comment by srikat** [comment]
Trying to do the same and facing the same issue of tabs not being clickable when their position is moved to the top via CSS.

What is the fix?
