### ISSUE TITLE
After refreshing, the block tab is blank

### ISSUE THREAD

**Issue by usoonees** [pengx17/logseq-plugin-tabs#47]
The first tab is page, the second tab is block.

Page tab is normal, but block tab is empty after refreshing.

![Jun-14-2022 19-27-25](https://user-images.githubusercontent.com/56818734/173567020-10de988b-5fb6-43b9-bbb4-bfa901a97edc.gif)

**Comment by pengx17** [comment]
I believe this is because the UUID of the block has changed after refresh. I guess in this case the second tab is considered as deleted, since there is no clue to recover from that.

**Comment by usoonees** [comment]
Thanks a lot for fixing this bug!  I am so excited!

This plugin is so perfect for me now!!!

**Comment by pengx17** [comment]
@usoonees thanks for your patience! I just figured out how to fix this issue in a stable way :D
