### ISSUE TITLE
Tabs get in the way of content when scrolling down

### ISSUE THREAD

**Issue by nmartin84** [pengx17/logseq-plugin-tabs#5]
Great plugin! As title suggests, when scrolling, the tabs end up blocking view of the content. It's also possible for the tabs to catch focus of the cursor preventing the user from further scrolling. Is it possible from the plugin side to adjust the `#main-container` element and put a margin so that the content aligns with the tabs? This should help fix both problems and provide a more aesthetic feel.

default view:
![image](https://user-images.githubusercontent.com/38045018/133525714-d76a64ce-d9da-4c68-9567-94b66f8a00ed.png)

`#main-container { margin-top: 30px }`
![image](https://user-images.githubusercontent.com/38045018/133525741-63511418-7075-46c9-a4b6-b9573b80e675.png)

**Comment by pengx17** [comment]
Hi @nmartin84 , I do not want to make the plugin to take too much visual space by adding global padding to the preview.
Alternatively, at the beginning I added a background to the plugin to make the controlling area more standing out, but now it's background is transparent to make this plugin easier to adapt for different themes. If you would like to have a background for it, you can specify a customized background for this plugin like this:

```css
iframe#logseq-tabs {
    background: red;
}
```
