### ISSUE TITLE
[Feature] Close button should be on the left, at least on the Mac

### ISSUE THREAD

**Issue by huyz** [pengx17/logseq-plugin-tabs#51]
On macOS, just as with macOS Safari, [VS Code](https://github.com/microsoft/vscode/issues/88604), [IntelliJ](https://www.jetbrains.com/help/idea/settings-editor-tabs.html#appearance), the close button on the tab should default to being shown on the left of the tab, not the right—or at least an option should be offered.

Beyond esthetics, there's a reason why the `X` button should be on the left: it's much easier to close a bunch of tabs in rapid succession: just keep clicking X and the current tab will be replaced by the one on the right, which will have its X in the same spot—so that you can easily click again. So it's just smarter.

**Comment by pengx17** [comment]
I believe it is better to have a setting to let the user customize the positioning of the close button. 👍
