### ISSUE TITLE
Shortcut conflict

### ISSUE THREAD

**Issue by manfredlotz** [pengx17/logseq-plugin-tabs#53]
This is logseq 0.7.7-1 on Linux. When installing `tabs` plugin I get

![image](https://user-images.githubusercontent.com/192842/181173035-d01fdf6d-7241-4aff-b065-a459e87712d4.png)

**Comment by dustinosity** [comment]
same issue here

**Comment by pengx17** [comment]
As it is stated in the error dialog, there are shortcut conflicts. You may want to change the tabs' toggle pin shortcut from the plugin's setting page to another to mute the issue.

**Comment by manfredlotz** [comment]
I understood the error message. Unfortunately, I did not find a way to list all given shortcuts so that it is easier to find a suitable one for tabs-toggle-pin.

My suggestion would be that the default shortcuts defined in `tabs` should not interfere with the basic shortcuts of Logseq. 

Any recommendation what a suitable shortcut could be for tabs-toggle-pin.

**Comment by pengx17** [comment]
@manfredlotz you are right, I did not anticipate that this could someday conflict with the default shortcut of Logseq. I will push a fix to change the pin tab short cut to as unset, because I am bad at choosing the right one.

**Comment by manfredlotz** [comment]
@pengx17 Yes, it is difficult to find an alternate shortcut. Thank you very much.
