### ISSUE TITLE
[feature req] Allow to open tab in side bar, using SHIFT+CLICK

### ISSUE THREAD

**Issue by emms007** [pengx17/logseq-plugin-tabs#56]
Hi
Having a dual view of main view and sidebar view in logseq is great;
It would be nice to have this logic also applicable using the TAB list. 

For instance : I have a sticky tab. If I want to open it in the main page I click on it (as today). If I wish to open it on the sidebar, I'd SHIFT+CLICK on it (new feature)

**Comment by AvijeetPrasad** [comment]
I would love to have this feature as well :)
