### ISSUE TITLE
not possible to open new tab from search

### ISSUE THREAD

**Issue by myownstandard** [pengx17/logseq-plugin-tabs#6]

**Comment by pengx17** [comment]
This requires Logseq to provide a hint to the destination of the actual page name or block ref in the search result, which is currently missing.

**Comment by nelson-dai-17Live** [comment]
Hi, 
This is an important feature for me.
May I know the status, is it possible now?

**Comment by yingzhu146** [comment]
Hi @pengx17 thanks a lot for the fantastic work! How do I use this (either keyboard or mouse?) I  tried cmd+enter/ctrl+enter via keyboard or cmd+click/ctrl+click via keyboard+mouse. If there's a config setting I've missde let me know - I just updated to 1.14.1 and restarted logseq so version should be correect.

**Comment by codeRSH** [comment]
Hi,

I am also not able to figure out how to enable this feature. I would especially appreciate if there is a keyboard shortcut to open a new tab from the search box.

**Comment by ElectricBoot** [comment]
> Hi [@pengx17](https://github.com/pengx17) thanks a lot for the fantastic work! How do I use this (either keyboard or mouse?) I tried cmd+enter/ctrl+enter via keyboard or cmd+click/ctrl+click via keyboard+mouse. If there's a config setting I've missde let me know - I just updated to 1.14.1 and restarted logseq so version should be correect.

These shortcuts don't work for me also.
Can anyone reply if it works for someone?
This issue was closed because the feature has been added OR the feature is not possible to add?
