### ISSUE TITLE
“不向右隐藏”的功能

### ISSUE THREAD

**Issue by msjsc001** [pengx17/logseq-plugin-tabs#60]
开发者您好，标签能不能添加一个“不向右隐藏”的功能选项。

有时会打开多个页面同时使用，打开的特别多的时候，标签就会隐藏到最右看不到，这时可以用ctrl+tab快捷键切换标签，但标签多的情况下这种快捷键的操作也不是很便捷，能不能添加一个标签不向右隐藏全显在当前页面的功能。

**Comment by pengx17** [comment]
确实，不过目前我还没精力做这个需求，先标记成help wanted了。

**Comment by pengx17** [comment]
Should be a duplicate of #9
