### ISSUE TITLE
Tab Not Clearing & Showing Pin Icon

### ISSUE THREAD

**Issue by edwarddarrah** [pengx17/logseq-plugin-tabs#70]
I am not able to clear this tab. I also don't know why the pin icon is appearing. Any suggestions would be helpful. Running the latest Beta version.

[
![Logseq_Pin_Issue](https://user-images.githubusercontent.com/96745845/213856927-4f09d95c-a365-4ccc-97a2-f25f13f54b5d.png)
](url)

**Comment by Holanda73** [comment]
you double clicked on it which means you pinned it. You need to unpin by double clicking on the tab.

**Comment by edwarddarrah** [comment]
Thanks. I was able to figure it out. I appreciate the reply!
