### ISSUE TITLE
logseq-tab-toggle-pin ctrl+p Keyboard shortcut conflicts with existing shortcut: editor/up

### ISSUE THREAD

**Issue by bigFin** [pengx17/logseq-plugin-tabs#72]
Toggle pin ctrl+p conflicts with default keyboard shortcut.

`:plugin.logseq-tabs/logseq-tab-toggle-pin ctrl+p Keyboard shortcut conflicts with existing shortcut: editor/up`

**Comment by dyllan-to-you** [comment]
There's currently a setting `tabs:toggle-pin` in the plugin settings to change the keyboard shortcut. That should solve your problem
