### ISSUE TITLE
Tabs conflict with the Agenda Plugin

### ISSUE THREAD

**Issue by ryepesg** [pengx17/logseq-plugin-tabs#73]
When using Tabs with the Agenda Plugin (https://haydenull.github.io/logseq-plugin-agenda), the shortcut to change to the next or previous tabs doesn't work

Related issue:
- https://github.com/yoyurec/logseq-awesome-ui/issues/39

**Comment by pengx17** [comment]
You can configure plugin shortcuts in the plugin settings. There is no good way to avoid conflict right now.

**Comment by yoyurec** [comment]
i think it's a question to AsesomeUI, cose natively Agenda on top of all Logseq area and you can't switch tabs )

**Comment by yoyurec** [comment]
with disabled AwesomeUI and some devtools tunig it clearly that it's my side issue

**Comment by ryepesg** [comment]
Thank you very much @yoyurec for investigating this! I am closing the issue here then
