### ISSUE TITLE
Cannot change tabs by clicking on them but keyboard shortcuts still work

### ISSUE THREAD

**Issue by yougotwill** [pengx17/logseq-plugin-tabs#87]
Just updated to `Version 0.9.11 (64)` and I can no longer click on the tabs at all: no pinning, closing, or changing. Keyboard shortcuts still work though.

**Comment by DutchPete** [comment]
I have the same, although when I reload Logseq everything works again …… until it does not.

**Comment by dnecklesportfolio** [comment]
I have the same issue. I am on logseq Version 0.9.11 (64) and Mac os x ventura 13.3.1

**Comment by reprintsev** [comment]
I have the same issue when the "Native title bar" setting is enabled. If the setting is turned off, then everything works.
Logseq 0.9.11 on Windows 10 x64.

**Comment by sunzy** [comment]
same issue, Logseq 0.9.11 on Win10/Win11

**Comment by AlienOctopus** [comment]
This no longer appears to be an issue as of the latest Logseq update to 0.9.14

**Comment by yougotwill** [comment]
@AlienOctopus I have just updated to v0.9.14 and the issue is still there. It seems to randomly come and go. 

Also macOS venture 13.5

**Comment by DutchPete** [comment]
I agree with @yougotwill.

**Comment by andupaz** [comment]
maybe @pengx17 can tell us how we can support this plugin

**Comment by pengx17** [comment]
@xyhp915 could you please help with this issue?

**Comment by yougotwill** [comment]
A quick fix for this bug I have found is opening and closing the Developer Tools (macOS shortcut `CMD+Shift+I`) Possibly the bug has something to do with which areas of the UI are focused on.

**Comment by DutchPete** [comment]
@yougotwill I am on macOS and regularly open the Developer Tools, but it has not made an iota of difference for me.

**Comment by yougotwill** [comment]
> @yougotwill I am on macOS and regularly open the Developer Tools, but it has not made an iota of difference for me.

Strange. Sorry to hear that. Well works for me. `macOS 13.5.2 (22G91) Logseq Version 0.9.17 (70)`

**Comment by DutchPete** [comment]
I am on macOS 13.5 and on Logseq 0.9.17.
Anyway, I am glad it works for you, and perhaps for others too.

**Comment by andupaz** [comment]
I’m on Windows 11 and Logseq Version 0.9.17 and opening the Developer Tool does absolutely nothing to the tabs.

**Comment by yoyurec** [comment]
Windows 11,
to fix: set "Native title bar" settings to **enabled**

**Comment by DutchPete** [comment]
@yoyurec: how about macOS?

**Comment by AlienOctopus** [comment]
I've never seen this option on Mac:

"_Native title bar" settings to enabled_"

@DutchPete still not working on Logseq Version 0.9.18 (71)

**Comment by DutchPete** [comment]
@AlienOctopus: even with 0.9.18 (71) it is not working.

**Comment by AlienOctopus** [comment]
Logseq Version: 0.9.18
macOS: 13.6

 This plugin works fine until the window size is modified in any way.

Tabs become inactive after window size changes.

**Comment by yougotwill** [comment]
Thank you @xyhp915! 🙏
