### ISSUE TITLE
Tabs name is showing incorrect

### ISSUE THREAD

**Issue by manvibharat** [pengx17/logseq-plugin-tabs#88]
Hi
This is a a very minor issue. In my system when I open journal page the the Tab shows it as **gj** . I tried reinstalling the plugin but not luck. I attach the screen shot for the reference. On my other system it works just fine. That is it shows Journals as the tab name.

![Screenshot from 2023-09-04 20-04-25](https://github.com/pengx17/logseq-plugin-tabs/assets/25891296/206c0f1d-9db8-4138-9b56-d14046c712c3)

**Comment by manishjhawar** [comment]
I'm having the exact same issue although the look and feel is different for me:

![image](https://github.com/pengx17/logseq-plugin-tabs/assets/712643/555322ca-14f1-4c65-9472-6f687e7386c6)

Also sometimes, while the tab title remains the same, the page shows up as a regular page for "gj":

![image](https://github.com/pengx17/logseq-plugin-tabs/assets/712643/3471f0d2-06c1-4254-b0b5-ede582984895)

**Comment by nanonandi** [comment]
It happens to me too, when two tabs are open, closing the one takes me to gj page

**Comment by Gitbreast** [comment]
Same. After clear cache on 0.10.1, Journal became “gj”.
Btw, good work upstairs!
<img width="238" alt="image" src="https://github.com/pengx17/logseq-plugin-tabs/assets/96460796/82917eca-8706-4f07-bdf4-272cdb1bd530">

**Comment by ksqsf** [comment]
The upstream seems unresponsive. Meanwhile, you can use this workaround:

1. View → Toggle Developer Tools.
2. In the console, copy&paste `localStorage.setItem("journalsString", "Journals")` and press Enter. `Journals` here can be replaced by your preferred tab name.
